In [4]:
#variaabels and data types
a =3
print(a)
print(type(a))

3
<class 'int'>

In [9]:
#List Data type -> Mutable data type
list1 = str
print(list1)
List2 = [1,2,4,5,6,'chaitanya']
print(List2)
# List through constructor
l = list({2,3,5,7})
print(l)
print(type(l))

Chaitanya
[1, 2, 4, 5, 6, 'chaitanya']
[2, 3, 5, 7]
<class 'list'>

In [6]:
#String variable
str = "Chaitanya"
print(str)
print(type(str))

Chaitanya
<class 'str'>

In [5]:
#float variable
b = 3.21
print(type(b))

<class 'float'>

In [18]:
#Tuple Data type -> Order is sorted fasion
# Duplicates are not allowesd

tup1 = tuple({2,3,4,51,51,5})
print(tup1)
print(type(tup1))

(2, 3, 4, 5, 51)
<class 'tuple'>

In [1]:
print("Hi Chaitanya ")

Hi Chaitanya

In [25]:
#frozenset in  python -> Immutable in nature
fs = frozenset(set([2,1,3,4]))
print(fs)
print(type(fs))

frozenset({1, 2, 3, 4})
<class 'frozenset'>

In [22]:
#set data type in python' -> Mutable in nature
s1 = set(['c','c','h','x'])
print(s1)

{'x', 'h', 'c'}

In [51]:
#OPRATION ON LIST
l1 = list([2,3,1,4,5])
l1.sort()
print(l1)

l1.append(0.1)
print(l1)
l1.insert(2,32)
print(l1)
l1.sort()
l1.pop()
print(l1)
l1.reverse()
print(l1)
l1.index(0.1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 0.1]
[1, 2, 32, 3, 4, 5, 0.1]
[0.1, 1, 2, 3, 4, 5]
[5, 4, 3, 2, 1, 0.1]

5

In [65]:
#Oprations on Tuple data type
tup = {2,1,3,5,6}
print(tup)
#print(tup[3])  #-> Index based accessing is not allowed in python
fruits = tuple({"Mango","Banana","Apple","Kivi","Orange"})
print(fruits)
#fruits = fruits.count()
print(fruits)
print(type(fruits))
#print(fruits.count())

{1, 2, 3, 5, 6}
('Orange', 'Apple', 'Kivi', 'Mango', 'Banana')
('Orange', 'Apple', 'Kivi', 'Mango', 'Banana')
<class 'tuple'>

In [67]:
#Boolean Datatype
a = True
print(a)
print(type(a))

True
<class 'bool'>

In [79]:
#Dictonary dataType
d1 ={"name":"Chaitanya","age":19,"college":"GPCS"}
print(d1)
print(type(d1))

#Using set as a key in Dictonary
s1  = {1,2,3}
print(type(s1))
s1 = frozenset(s1)
print(type(s1))
print(s1)
#dict2 = {s1 :[2,3,45]}
dict2 = dict(s1=[2,3,45])
print(dict2)
#Accessing the vales , keys and items of the dictonary data type
print(type(dict2))
print(dict2.values())
print(dict2.keys())
print(dict2.items())

{'name': 'Chaitanya', 'age': 19, 'college': 'GPCS'}
<class 'dict'>
<class 'set'>
<class 'frozenset'>
frozenset({1, 2, 3})
{'s1': [2, 3, 45]}
<class 'dict'>
dict_values([[2, 3, 45]])
dict_keys(['s1'])
dict_items([('s1', [2, 3, 45])])

In [36]:
#Oprations on the String
string  = "Chaitanya Jagannath Kale"
print(string.count)
print(string)
print(string[3])
print(string[-2])
print(string[0:-15])
print(string.capitalize())
print(string.replace("Chaitanya","Amruta"))
print(string.replace("Chaitanya","Divya"))

<built-in method count of str object at 0x7da0ef78f0f0>
Chaitanya Jagannath Kale
i
l
Chaitanya
Chaitanya jagannath kale
Amruta Jagannath Kale
Divya Jagannath Kale